AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance Creation'

Parameters:
  devops-vpc-stack:
    Type: String
    Description: The name of the VPC stack to import values from

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07d20571c32ba6cdc
      KeyName: cdpipeline  
      SubnetId: 
        Fn::ImportValue: 
          Fn::Sub: 
            - "${VpcStack}-Subnet1ID"
            - VpcStack: !Ref devops-vpc-stack
      SecurityGroupIds: 
        - Fn::ImportValue: 
            Fn::Sub:
              - "${VpcStack}-SecurityGroupID"
              - VpcStack: !Ref devops-vpc-stack