AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance Creation'

Parameters:
  VpcStackId:
    Type: String
    Description: The Stack ID of the VPC stack to import values from
    Default: arn:aws:cloudformation:eu-west-2:842387632939:stack/devops-vpc-stack/38bdf580-4b43-11ef-bb4d-06d3e848c961

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07d20571c32ba6cdc
      KeyName: cdpipeline  
      SubnetId: 
        Fn::ImportValue: 
          !Sub "${VpcStackId.Outputs.Subnet1ID}"
      SecurityGroupIds: 
        - Fn::ImportValue: 
            !Sub "${VpcStackId.Outputs.SecurityGroupID}"