AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS Instance CloudFormation Template'

Parameters:
  DBInstanceIdentifier:
    Type: String
    Description: The database instance identifier
  
  DBEngine:
    Type: String
    Default: mysql
    AllowedValues:
      - mysql
      - postgres
      - sqlserver-ex
    Description: The database engine to use

  DBInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: The database instance class

  DBName:
    Type: String
    Description: The name of the database to create

  DBUsername:
    Type: String
    Description: The master username for the database

  DBPassword:
    Type: String
    NoEcho: true
    Description: The master password for the database

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      Engine: !Ref DBEngine
      DBInstanceClass: !Ref DBInstanceClass
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: '20'
      PubliclyAccessible: false
      MultiAZ: false

Outputs:
  RDSEndpoint:
    Description: 'RDS Instance Endpoint'
    Value: !GetAtt RDSInstance.Endpoint.Address