name: Delete CloudFormation Stack

on:
  workflow_dispatch:

jobs:
  delete_stack:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Delete CloudFormation stack
        run: |
          aws cloudformation delete-stack --stack-name DSAccessRoleStack
