name: Delete VPC CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type "DELETE" to confirm stack deletion'
        required: true

env:
  AWS_REGION: eu-west-2 # Change this to your VPC's AWS region
  STACK_NAME: devops-vpc-stack  # The name of your VPC stack

jobs:
  delete_stack:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_delete == 'DELETE'
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Delete CloudFormation stack
      run: |
        echo "Deleting stack ${{ env.STACK_NAME }}"
        aws cloudformation delete-stack --stack-name ${{ env.STACK_NAME }}
        
        echo "Waiting for stack deletion to complete"
        aws cloudformation wait stack-delete-complete --stack-name ${{ env.STACK_NAME }}
        
        echo "Stack deletion completed"

    - name: Check stack deletion
      run: |
        if aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} 2>&1 | grep -q 'does not exist'; then
          echo "Stack ${{ env.STACK_NAME }} has been successfully deleted"
        else
          echo "Stack deletion failed or stack still exists"
          exit 1
        fi