name: Deploy Route 53 Record

on:
  push:
    branches:
      - dev-m


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file DNS/route-record-template.yml \
          --stack-name route53-dns-record \
          --parameter-overrides \
            HostedZoneName=example.com. \
            RecordName=mysite.example.com. \
            RecordType=A \
            TTL=900 \
            IPAddresses=192.168.0.1,192.168.0.2 \
          --capabilities CAPABILITY_IAM