name: Deploy Route 53 Hosted Zone

on:
  push:
    branches: [ dev-m ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION}}

    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file DNS/route-template.yml \
          --stack-name route53-hosted-zone \
          --parameter-overrides DomainName=example.com \
          --capabilities CAPABILITY_IAM

    - name: Verify stack deployment
      run: |
        aws cloudformation describe-stacks \
          --stack-name my-route53-hosted-zone \
          --query "Stacks[0].StackStatus" \
          --output text