name: Deploy RDS Aurora

on:
  push:
    branches:
      - dev-m

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file Database/rds-aurora-template.yml \
          --stack-name my-rds-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            MasterUserPassword=${{ secrets.MASTER_USER_PASSWORD }} \
            VpcId=${{ secrets.VPC_ID }} \
            MasterUsername=${{ secrets.MASTER_USERNAME }} \
            SubnetIds=${{ secrets.SUBNET_ID }} \
            SecurityGroupIds=${{ secrets.SECURITY_GROUP_ID }}
