name: Deploy IAM Role with CloudFormation

on:
  push:
    branches:
      - dev-m  # Specify the branch to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Specify your AWS region

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://IAM/rds-iam-role.yml

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file IAM/rds-iam-role.yml \
            --stack-name RDSAccessRoleStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --region eu-west-2

      - name: Confirm Deployment
        run: |
          aws cloudformation describe-stacks --stack-name RDSAccessRoleStack
