name: Deploy RDS Instance

on:
  push:
    branches:
      - dev-m

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-west-2'

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file Database/rds-aurora-template.yml \
            --stack-name my-rds-stack \
            --capabilities CAPABILITY_NAMED_IAM
